apiVersion: v1
kind: Namespace
metadata:
  name: saga
  labels:
    name: saga
    app: saga
    environment: production
  annotations:
    description: "SAGA - Sistema de Gerenciamento de Treinos"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: saga-quota
  namespace: saga
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: saga-limits
  namespace: saga
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container 