apiVersion: v1
kind: Secret
metadata:
  name: saga-secrets
  namespace: saga
  labels:
    app: saga
type: Opaque
data:
  # Secrets em base64 - ALTERAR EM PRODUÇÃO
  # Para gerar: echo -n "seu-valor" | base64
  jwt-secret: c2V1X2p3dF9zZWNyZXRfc3VwZXJfZm9ydGVfZGVfcGVsb19tZW5vc18yNTZfYml0cw==
  db-password: c3VhX3NlbmhhX2ZvcnRlX2FxdWk=
  redis-password: cmVkaXNfc2VuaGFfZm9ydGU=
  grafana-password: Z3JhZmFuYV9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: saga-tls
  namespace: saga
  labels:
    app: saga
type: kubernetes.io/tls
data:
  # Certificados SSL/TLS - substituir por certificados reais
  tls.crt: LS0tLS1CRUdJTi... # Certificado base64
  tls.key: LS0tLS1CRUdJTi... # Chave privada base64
---
apiVersion: v1
kind: Secret
metadata:
  name: saga-registry
  namespace: saga
  labels:
    app: saga
type: kubernetes.io/dockerconfigjson
data:
  # Credenciais do registry Docker - se necessário
  .dockerconfigjson: eyJhdXRocyI6e319 