[phases.setup]
nixPkgs = ['...', 'maven']

[phases.build]
cmds = ['mvn clean package -DskipTests -Dmaven.repo.local=/tmp/m2']

[phases.start]
cmd = 'find target -name "*.jar" -exec java -Dspring.profiles.active=railway -jar {} \;'

[variables]
MAVEN_OPTS = '-Xmx1024m' 